steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'gcr.io/${PROJECT_ID}/github.com/pylons-tech/pylons', 
          '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
          'gcr.io/${PROJECT_ID}/github.com/pylons-tech/pylons']

# fetch GKE cluster credentials to be used for helm step
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']


# run helm command to install/upgrade
- name: 'gcr.io/rimusz-lab1/cloud-builders-helm'
  args: ['upgrade', '--install', 'validator-1', '--namespace', 'default', 'deploy/validator-1/']
  env:
  - 'KUBECONFIG=/workspace/.kube/config'
  - 'HELM_REPO_NAME=validator-1'
  - 'HELM_REPO_URL=deploy/validator-1/'

options:
  logging: CLOUD_LOGGING_ONLY