
steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
          'gcr.io/${PROJECT_ID}/github.com/pylons-tech/pylons', 
          '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 
          'gcr.io/${PROJECT_ID}/github.com/pylons-tech/pylons']

# fetch GKE cluster credentials to be used for helm step
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']

- name: gcr.io/$PROJECT_ID/cloud-builders-community/helm
  id: Deploy chart
  args:
    - upgrade
    - -i
    - validator-1
    - --namespace
    - default
    - ./deploy/validator-1
    - -f
    - ./deploy/validator-1/values.yaml
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true


options:
  logging: CLOUD_LOGGING_ONLY

