version: '3'

services:
  node:
    container_name: node
    build:
      context: .
      args:
        - BINARY_VERSION=v1.0.0-rc2
    ports:
      - "26657:26657"
      - "1317:1317"
    volumes:
      - ./debug:/debug
      - ./trace.rb:/home/big-dipper/trace.rb
      - ./bigquery_keyfile.json:/home/big-dipper/bigquery_keyfile.json