apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $files := .Files }}
  {{- range tuple "validator-1.yaml"}}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}