apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.toml: |-
{{ .Files.Get "config/config.toml" | indent 4}}
  app.toml: |-
{{ .Files.Get "config/app.toml" | indent 4}}
  client.toml: |-
{{ .Files.Get "config/client.toml" | indent 4}}
