name: Flutter

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - uses: subosito/flutter-action@v2
         with:
            channel: 'stable' # or: 'beta' or 'master'
       - run: |
          cd easel
          flutter lint
