name: proto_checks

on: [pull_request]

jobs:
  proto_checks:
    name: proto lint, breaking changes detection and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Fetching base branch
        run: |
                    git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      # - name: Running linter, checking breaking changes
      #   run: |
      #     buf lint
      #     buf breaking --against ".git#branch=${{ github.base_ref }}"          
      - name: Running buf build
        working-directory: ${GITHUB_WORKSPACE}/proto
        run: |
          buf build --error-format=json
      - name: Generating protos
        working-directory: ${GITHUB_WORKSPACE}/proto
        run: |
          buf generate --template ./proto/buf.gen.gogo.yaml        
        env:
          GEN_OUT_DIR: contracts/build/go
          PROTO_DIR: contracts/proto